<a href="https://colab.research.google.com/github/tomdeb88/Data_Science_practise/blob/main/Numpy/01_numpy_wprowadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
np.__version__

'1.23.5'

In [5]:
# dir(np)

In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [7]:
 x=np.array([1,3])
 x

array([1, 3])

In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
y=np.array([1,2.3,1.4])

In [14]:
y.dtype

dtype('float64')

2 D

In [15]:
z=np.array([[1,2],[-3,1]])
z

array([[ 1,  2],
       [-3,  1]])

In [16]:
z.ndim

2

In [17]:
z.shape

(2, 2)

In [18]:
t=np.array([[1,2,3],[4,2,1]])
t

array([[1, 2, 3],
       [4, 2, 1]])

In [19]:
t.shape

(2, 3)

3 D

In [20]:
x=np.array(
    [[[1,2,3],
      [2,3,4]],

    [[1,2,3],
     [3,4,5]]])

x

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [21]:
x.ndim

3

In [22]:
x.shape

(2, 2, 3)

Typy danych

In [23]:
A=np.array([1,2,3])
A.dtype

dtype('int64')

In [24]:
b=np.array([1.9,2.4,3],dtype='int')
b.dtype

dtype('int64')

In [25]:
b

array([1, 2, 3])

In [26]:
c=np.array([True,False])

In [27]:
c

array([ True, False])

In [28]:
d=np.array([12,23,45],dtype=np.int8) # albo uint8--> unsigned int

In [29]:
d.dtype

dtype('int8')

Tworzenie tablic

In [30]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros(shape=(4,10),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.full(shape=(3,3),fill_value=4,dtype='float')

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [36]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
np.arange(start=100,stop=0,step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [38]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [39]:
np.linspace(start=0,stop=1,num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [40]:
e=np.arange(0,15)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
e.reshape((3,5)) #-----> iloczyn argumentow shape musi wynosic 15 (ilosc elemntow tablicy e)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
e.reshape((5,-1)) # ---> (-1) chcemy miec 3 wiersze a niech numpy dobierze odpowiednia liczbe kolumn

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [43]:
a=np.array([1,2,3,4])
b=np.array([2,-3,4,5])
print(a)
print(b)

[1 2 3 4]
[ 2 -3  4  5]


Zeby dodawac tablice rozmiar tablic musi sie zgadzac

In [44]:
a+b

array([ 3, -1,  7,  9])

In [45]:
a-b

array([-1,  5, -1, -1])

In [46]:
a*b

array([ 2, -6, 12, 20])

In [47]:
a/b  #---> pamietac nalezy,ze nie moze byc zero w jednej z tablic

array([ 0.5       , -0.66666667,  0.75      ,  0.8       ])

In [48]:
print(a)
a+3 #----> dodaje 3 do kazdego elementu

[1 2 3 4]


array([4, 5, 6, 7])

In [49]:
a + 3*b

array([ 7, -7, 15, 19])

Metody arytmetyczne do wykonywania na tablicach

In [50]:
np.add(a,b)  #np.subtract(a,b), np.multiply(a,b), np.divide(a,b)

array([ 3, -1,  7,  9])

Mnożenie macierzowe

In [51]:
#dwie macierze kwadratowe
x=np.array([[1,3],[-2,0]])
y=np.array([[6,0],[-1,2]])
print(x,'\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [52]:
x*y

array([[6, 0],
       [2, 0]])

In [53]:
#mnozenie macierzy
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])

In [54]:
x.dot(y)  #----> metoda do mnozenia macierzy

array([[  3,   6],
       [-12,   0]])

In [55]:
y.dot(x)  # ---> mnozenie macierz nie jest przemienne

array([[ 6, 18],
       [-5, -3]])

In [56]:
x @ y #           '@'   ---> symbol do mnoezenia macierzy

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [57]:
np.random.seed(0) #--> ustalamy ziarno losowe zeby zawsze otrzymac taki sam wynik losowania

In [58]:
np.random.randn() # losowa liczba z rozkladu normalnego

1.764052345967664

In [59]:
np.random.randn(10)  # tablica zawierajaca 10 losowo wygenerowanych elementow z rozkladu standardowego normalnego czyli o sredniej 0 i odchyleniu standardowym 1

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [60]:
np.random.randn(10,4)  #10 libcza wierszy/obserwacji / 4 liczba kolumn/ cech ///  np do stworzenia histogramow dla rozkladu normalnego

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [61]:
np.random.rand() # wartosc losowa od 0 do 1 (bez jedynki)

0.1965823616800535

In [62]:
np.random.rand(5)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841])

In [63]:
np.random.rand(5,4)

array([[0.97645947, 0.4686512 , 0.97676109, 0.60484552],
       [0.73926358, 0.03918779, 0.28280696, 0.12019656],
       [0.2961402 , 0.11872772, 0.31798318, 0.41426299],
       [0.0641475 , 0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 , 0.9292962 ]])

In [64]:
np.random.randint(10)  # zwraca liczbe losowa od 0 do 9

8

In [65]:
np.random.randint(low=10,high=100,size=10)  # size ile poztrebujemy wygenerowac liczb

array([21, 12, 61, 90, 42, 64, 10, 48, 29, 56])

In [66]:
np.random.choice([3,7,9,12]) # losowo wybiera jedna liczbe z naszego przekazanego obiektu

9

In [67]:
np.random.choice(['python','java','sql'])

'python'

In [68]:
data =np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.random.shuffle(data)  # od razu zmienia dane w obiekcie
data

array([4, 0, 1, 7, 6, 3, 2, 5, 9, 8])

Podstawowe funkcje w Numpy

In [70]:
np.exp(1) # potegowanie

2.718281828459045

In [71]:
np.sqrt(9) #  pierwiastek kwadratowy

3.0

In [72]:
np.all([1,2,5]) # wartosci logiczne, jezeli wszystkie elementy zwroca True wartosc z all bedzie True

True

In [73]:
np.all([0,3,5])

False

In [74]:
np.any([0,0,1]) # funkcja any spr czy jakikolwiek obiekt jest prawda i wtedy zwraca True

True

In [75]:
np.any([0,0,0])

False

In [76]:
q=np.random.rand(5)
q

array([0.24875314, 0.57615733, 0.59204193, 0.57225191, 0.22308163])

In [77]:
np.argmax(q)  # zwraca index najwiekszej wartosci

2

In [78]:
q[np.argmax(q)]

0.592041931271839

In [79]:
np.argmin(q)

4

In [80]:
q[np.argmin(q)]

0.2230816326406183

In [81]:
np.argsort(q) # sortuje wartosci od najmniejszej do najwiekszej podajac indexy

array([4, 0, 3, 1, 2])

In [82]:
q[np.argsort(q)]

array([0.22308163, 0.24875314, 0.57225191, 0.57615733, 0.59204193])

In [83]:
np.max(q)

0.592041931271839

In [84]:
np.min(q)

0.2230816326406183

In [85]:
np.mean(q)

0.4424571895282251

In [86]:
np.median(q)

0.5722519057908734

In [87]:
np.std(q)  # odchylenie standardowe

0.1689644249393515

Indeksowanie/ wycinanie

In [88]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [89]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [90]:
A[2]

2

In [91]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [92]:
A[:2]

array([0, 1])

In [93]:
A[3:5]

array([3, 4])

In [94]:
A=A.reshape(4,5)

In [95]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [96]:
A[0]

array([0, 1, 2, 3, 4])

In [97]:
A[1]

array([5, 6, 7, 8, 9])

In [98]:
A[:,0]

array([ 0,  5, 10, 15])

In [99]:
A[:,-1]

array([ 4,  9, 14, 19])

In [100]:
A[1,1]

6

In [101]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [102]:
A[1,2]=0

In [103]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  0,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [104]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  0,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [105]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 0 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [107]:
for row in A:
  print(row[0])  # row[:3]

0
5
10
15


In [109]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
0
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana wymiaru tablic

In [110]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  0,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [111]:
A.shape

(4, 5)

In [112]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [113]:
A.ravel()  # wyplaszczamy tablice, wracamy do postaci jednowymiarowej

array([ 0,  1,  2,  3,  4,  5,  6,  0,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [115]:
A.T  # transponowanie czyli zamienianie kolumny na wiersze

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  0, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [117]:
A=np.arange(-10,10,0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [119]:
A.reshape(10,-1)  # ustawiamy tak zebysmy mieli 10 wierszy

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [120]:
A>0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [121]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [122]:
np.bitwise_and(A>-5,A<5)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [123]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [124]:
np.bitwise_or(A<-5,A>5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [125]:
A[np.bitwise_or(A<-5,A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])